import { Provider } from "react-redux";
import { Canvas } from "@/lib/reactThreeFiber";
import { Shadow } from "@/lib/reactThreeDrei";

import "@/styles/globals.scss";
import Footer from "@/components/footer";
import Header from "@/components/header";
import StarField from "@/components/header/StarField";

export const metadata = {
  icons: { icon: "/favicon.ico" },
  title: {
    default: "TBT",
    template: "&s | TBT",
  },
  description: "Generated by create next app",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 1,
  },
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafafa" },
    { media: "(prefers-color-scheme: dark)", color: "#151515" },
  ],
  appleWebApp: {
    title: "ChatGPT Next Web",
    statusBarStyle: "default",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        <div className="absolute inset-0 z-0">
          <Canvas className="h-screen w-screen" style={{ background: "black" }}>
            <Shadow
              color="black"
              colorStop={0}
              opacity={0.5}
              fog={false} // Reacts to fog (default=false)
            />
            <StarField count={5000} />
          </Canvas>
        </div>
        <main className="relative min-h-screen overflow-hidden">
          <div className="absolute left-0 top-0 z-10">{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
